name: dev.to

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        bash devto.sh src ${{ secrets.DEVTO_API_KEY }}
    - name: Commit files
      run: |
        git diff-index --quiet HEAD -- && exit 0
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/*.id
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
