
name: MdBook-GhPages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: remove front matter
      run : |
        mkdir tmp
        for file in src/*.md
        do
          sed '1 { /^---/ { :a N; /\n---/! ba; d} }' $file > tmp/${file:3}
          cat tmp/${file:3}
        done

    - name: initiate summary
      run: |
        echo "# Summary" > SUMMARY.md

    - name: prefix summary
      run: |
        [ -d prefix ] || exit 0
        for file in prefix/*.md
        do
          title=$(grep "^# " "$file" | head -n1)
          echo "[${title:2}](${file:7})" >> SUMMARY.md    
        done

    - name: create summary
      run: |
        for file in tmp/*.md
        do
          title=$(grep "^# " "$file" | head -n1)
          echo "- [${title:2}](${file:4})" >> SUMMARY.md
        done

    - name: mdbook suffix
      run: |
        [ -d suffix ] || exit 0
        echo "---" >> SUMMARY.md
        for file in suffix/*.md
        do
          title=$(grep "^# " "$file" | head -n1)
          echo "[${title:2}](${file:7})" >> SUMMARY.md    
        done

    - name: move summary
      run: |
        cat SUMMARY.md
        mv SUMMARY.md tmp

    - name: prefix copy
      run: |
        [ -d prefix ] || exit 0
        for file in prefix/*.md
        do cp "$file" tmp
        done

    - name: suffix copy
      run: |
        [ -d suffix ] || exit 0
        for file in suffix/*.md
        do cp "$file" tmp
        done

    - name: Emojify
      run: |
        curl https://raw.githubusercontent.com/mrowa44/emojify/master/emojify -o ./emojify
        chmod +x ./emojify
        for file in src/*.md
        do
          cat $file | ./emojify # just logging
          cat $file | ./emojify > ${file}.md
          mv ${file}.md ${file}
        done

    - name: build book
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - run: mdbook build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./book
